src/mini_buildd/urls.py
import logging

import django.views.generic.base
from django.urls import include, path, re_path
import django.conf.urls

from mini_buildd.config import URIS, Uri
import mini_buildd.admin
from mini_buildd.views import DefaultView, DirView, EventsView, BuildsView, RepositoriesView, BuildersView, APIView, SetupView, LogView, AccountRegisterView, AccountActivateView, AccountProfileView, ExceptionMiddleware

LOG = logging.getLogger(__name__)


def mbd_path(route, uri="view", view_cls=DefaultView):
    uri_obj = URIS[route][uri]
    name = route if uri == "view" else f"{route}-{uri}"
    path_func = re_path if uri_obj.django_with_path else path
    LOG.info(f"Adding url: {name} -> {uri_obj}")
    return path_func(uri_obj.django(), view_cls.as_view(), kwargs={"route": route, "name": name}, name=name)


# pylint: disable=invalid-name
urlpatterns = [
    # Redirect
    path("", django.views.generic.base.RedirectView.as_view(url=URIS["home"]["view"].django())),

    # /admin
    path(URIS["admin"]["view"].django(), mini_buildd.admin.site.urls),

    # /accounts/
    path(URIS["accounts"]["register"].django(), AccountRegisterView.as_view(), name="register"),
    path(URIS["accounts"]["activate"].django() + "<uidb64>/<token>/", AccountActivateView.as_view(), name="activate"),
    path(URIS["accounts"]["profile"].django(), AccountProfileView.as_view(), name="profile"),
    path(URIS["accounts"]["base"].django(), include("django.contrib.auth.urls")),

    # /mini_buildd/
    mbd_path("home"),
    mbd_path("events", view_cls=EventsView),
    mbd_path("events", uri="dir", view_cls=DirView),
    mbd_path("builds", view_cls=BuildsView),
    mbd_path("builds", uri="dir", view_cls=DirView),
    mbd_path("repositories", view_cls=RepositoriesView),
    mbd_path("repositories", uri="dir", view_cls=DirView),
    mbd_path("builders", view_cls=BuildersView),
    mbd_path("crontab"),
    mbd_path("api"),
    mbd_path("sitemap"),
    mbd_path("manual"),
    mbd_path("setup", view_cls=SetupView),
    mbd_path("log", view_cls=LogView),
]

# /mini_buildd/api/<call>/
for _NAME, _CALL in mini_buildd.api.CALLS.items():
    _URI = Uri(_CALL.uri())
    LOG.info(f"Adding API route: {_NAME}: {_URI}")
    urlpatterns.append(path(_URI.django(), APIView.as_view(), kwargs={"call": _CALL}, name=f"apicall_{_NAME}"))

django.conf.urls.handler400 = ExceptionMiddleware.bad_request
django.conf.urls.handler403 = ExceptionMiddleware.permission_denied
django.conf.urls.handler404 = ExceptionMiddleware.page_not_found
django.conf.urls.handler500 = ExceptionMiddleware.server_error

src/mini_buildd/models/distribution.py
import logging
import functools

import django.core.exceptions
import django.db
import django.utils.html

import mini_buildd.dist
import mini_buildd.files
import mini_buildd.sbuild

import mini_buildd.models.base
import mini_buildd.models.source

LOG = logging.getLogger(__name__)


class Suite(mini_buildd.models.base.Model):
    name = django.db.models.CharField(
        max_length=100,
        help_text="A suite to support, usually s.th. like 'experimental', 'unstable', 'testing' or 'stable'.")

    def __str__(self):
        return f"{self.name}"

    def clean(self, *args, **kwargs):
        super().clean(*args, **kwargs)
        self.mbd_validate_regex(r"^[a-z]+$", self.name, "name")


class SuiteOption(mini_buildd.models.base.Model):
    layout = django.db.models.ForeignKey("Layout",
                                         on_delete=django.db.models.CASCADE)
    suite = django.db.models.ForeignKey("Suite",
                                        on_delete=django.db.models.CASCADE)

    uploadable = django.db.models.BooleanField(
        default=True,
        help_text="Whether this suite should accept user uploads.")

    experimental = django.db.models.BooleanField(
        default=False,
        help_text="""
Experimental suites must be uploadable and must not
migrate. Also, the packager treats failing extra QA checks (like
lintian) as non-lethal, and will install anyway.
""")

    migrates_to = django.db.models.ForeignKey(
        "self", blank=True, null=True,
        on_delete=django.db.models.CASCADE,
        help_text="Give another suite where packages may migrate to (you may need to save this 'blank' first before you see choices here).")

    build_keyring_package = django.db.models.BooleanField(
        default=False,
        help_text="Build keyring package for this suite (i.e., when the resp. Repository action is called).")

    auto_migrate_after = django.db.models.IntegerField(
        default=0,
        help_text="For future use. Automatically migrate packages after x days.")

    not_automatic = django.db.models.BooleanField(
        default=True,
        help_text="Include 'NotAutomatic' in the Release file.")

    but_automatic_upgrades = django.db.models.BooleanField(
        default=True,
        help_text="Include 'ButAutomaticUpgrades' in the Release file.")

    class Meta(mini_buildd.models.base.Model.Meta):
        unique_together = ("suite", "layout")

    def __str__(self):
        return self.suite.name

    def clean(self, *args, **kwargs):
        super().clean(*args, **kwargs)
        if self.build_keyring_package and not self.uploadable:
            raise django.core.exceptions.ValidationError("You can only build keyring packages on uploadable suites!")
        if self.experimental and self.migrates_to:
            raise django.core.exceptions.ValidationError("Experimental suites may not migrate!")
        if self.experimental and not self.uploadable:
            raise django.core.exceptions.ValidationError("Experimental suites must be uploadable!")
        if self.migrates_to and self.migrates_to.layout != self.layout:
            raise django.core.exceptions.ValidationError("Migrating suites must be in the same layout (you need to save once to make new suites visible).")
        if self.migrates_to and self.migrates_to.uploadable:
            raise django.core.exceptions.ValidationError("You may not migrate to an uploadable suite.")

    @property
    def rollback(self):
        """Rollback field temporarily implemented as extra_option."""
        return int(self.mbd_get_extra_option("Rollback", "0"))

    def mbd_get_sort_no(self):
        """Compute number that may be used to sort suites from 'stable' (0) towards 'experimental'."""
        no = 0
        if self.uploadable:
            no += 5
        if self.migrates_to:
            no += 5
        if self.experimental:
            no += 20
        return no


class SuiteOptionInline(django.contrib.admin.TabularInline):
    model = SuiteOption
    extra = 1
    exclude = ("pickled_data", "extra_options",)


class Layout(mini_buildd.models.base.Model):
    MBD_HELP_EXTRA_OPTIONS = """
Meta-Distributions: META=CODENAME-SUITE[ META=CODENAME-SUITE[...: Support METAs alone as distribution identifier.

Meta distribution identifiers should be unique across all
repositories; usually, a layout with meta distributions should
only be used by at most one repository.

Example:
---
Meta-Distributions: unstable=sid-unstable experimental=sid-experimental
---

(See standard layout 'Debian Developer'): allows upload/testing of
packages (to unstable,experimental,..) aimed for Debian.
"""

    name = django.db.models.CharField(primary_key=True, max_length=100)

    suites = django.db.models.ManyToManyField(Suite, through=SuiteOption)

    # Version magic
    default_version = django.db.models.CharField(
        max_length=100, default="~%IDENTITY%%CODEVERSION%+1",
        help_text=("""\
Version string to append to the original version for automated ports; you may use these placeholders:

%IDENTITY%: Repository identity (see 'Repository').
%CODEVERSION%: Numerical base distribution version (see 'Source').
"""))

    mandatory_version_regex = django.db.models.CharField(
        max_length=100, default=r"~%IDENTITY%%CODEVERSION%\+[1-9]",
        help_text="Mandatory version regex; you may use the same placeholders as for 'default version'.")

    # Version magic (experimental)
    experimental_default_version = django.db.models.CharField(
        max_length=30, default="~%IDENTITY%%CODEVERSION%+0",
        help_text="Like 'default version', but for suites flagged 'experimental'.")

    experimental_mandatory_version_regex = django.db.models.CharField(
        max_length=100, default=r"~%IDENTITY%%CODEVERSION%\+0",
        help_text="Like 'mandatory version', but for suites flagged 'experimental'.")

    class Admin(mini_buildd.models.base.Model.Admin):
        inlines = (SuiteOptionInline,)

    def __str__(self):
        return f"{self.name}"

    def mbd_get_reverse_dependencies(self):
        """When the layout changes, all repos that use that layout also change."""
        return list(self.repository_set.all())


class ArchitectureOption(mini_buildd.models.base.Model):
    architecture = django.db.models.ForeignKey("Architecture",
                                               on_delete=django.db.models.CASCADE)
    distribution = django.db.models.ForeignKey("Distribution",
                                               on_delete=django.db.models.CASCADE)

    optional = django.db.models.BooleanField(
        default=False,
        help_text="Don't care if the architecture can't be build.")

    build_architecture_all = django.db.models.BooleanField(
        default=False,
        help_text="Use to build arch-all packages.")

    class Meta(mini_buildd.models.base.Model.Meta):
        unique_together = ("architecture", "distribution")

    def __str__(self):
        return f"{self.architecture} for {self.distribution}"

    def clean(self, *args, **kwargs):
        super().clean(*args, **kwargs)
        if self.build_architecture_all and self.optional:
            raise django.core.exceptions.ValidationError("Optional architectures must not be architecture all!")


class ArchitectureOptionInline(django.contrib.admin.TabularInline):
    model = ArchitectureOption
    exclude = ("pickled_data", "extra_options",)
    extra = 1


@functools.total_ordering
class Distribution(mini_buildd.models.base.Model):
    MBD_HELP_EXTRA_OPTIONS = f"""
===============================================================================================
Sbuild-Config-Blocks[-Top]: <BLOCK> ...: Use predefined sbuild config blocks (space-separated).
===============================================================================================
{mini_buildd.sbuild.CONFIG_BLOCKS.usage()}

===============================================================================================
Sbuild-Setup-Blocks[-Top]: <BLOCK> ...: Use predefined sbuild setup blocks (space-separated).
===============================================================================================
{mini_buildd.sbuild.SETUP_BLOCKS.usage()}

===============================================================================================
Autopkgtest-Mode: <MODE>: {mini_buildd.dist.SbuildCheck.desc()}
===============================================================================================
{mini_buildd.dist.SbuildCheck.usage()}

===============================================================================================
Internal-APT-Priority: <PRIORITY>: Set APT priority for internal apt sources in builds.
===============================================================================================
The default is 1, which means you will only build against newer
packages in our own repositories in case it's really needed by the
package's build dependencies. This is the recommended behaviour,
producing sparse dependencies.

However, some packages with incorrect build dependencies might
break anyway, while they would work fine when just build against
the newest version available.

You may still solve this on a per-package basis, using the
resp. upload option via changelog. However, in case you don't care
about sparse dependencies in this distribution in general, you can
pimp the internal priority up here.

Example: Always build against newer internal packages:
---
Internal-APT-Priority: 500
---
===============================================================================================
Deb-Build-Options: ...: Set extra build options.
===============================================================================================
Values to add to environment variable ``DEB_BUILD_OPTIONS`` used when building packages. See

* ``https://www.debian.org/doc/debian-policy/ch-source.html#debian-rules-and-deb-build-options`` and

src/mini_buildd/templates/mini_buildd/repositories/index.html
{% extends "mini_buildd/base.html" %}
{% block title %}{% block page_title %}{{ route|title }}{% endblock %}{% endblock %}
{% block subtitle %}{{ view.mbd_repositories|length }} repositories{% endblock %}
{% block menu_r %}
	<li>{% mbd_api_popup "keyring_packages" %}</li>
	<li>{% mbd_api_popup "test_packages" %}</li>
	<li><a href="{% url 'admin:mini_buildd_repository_changelist' %}"><img class="mbd-icon" src="{% static 'icons/categories/preferences-other.svg' %}" alt="Configure"></a></li>
{% endblock %}

{% block section %}
	{% for r in view.mbd_repositories %}
		<header class="mbd-grid-lcr">
			{% mbd_dict_get mbd.daemon.attention "repositories" as attention %}
			<h2 class="{{ attention|yesno:'mbd-attention,' }}" title="{{ attention|join:"&#10;" }}">{{ r }}</h2>
			<nav>
			</nav>
			<nav>
				<ul>
					<li>{% mbd_api_popup "uploaders" value_repositories=r.identity %}</li>
					<li><a href="{% url 'admin:mini_buildd_repository_change' r.identity %}"><img class="mbd-icon" src="{% static 'icons/categories/preferences-other.svg' %}" alt="Configure"></a></li>
				</ul>
			</nav>
		</header>

		{% for d in r.mbd_sorted_distributions %}
			<details>
				<summary><strong>{{ d }}</strong></summary>

				{% mbd_token as table_id %}
				<table id="{{ table_id }}">
					{% mbd_datatable table_id no_search='[1, 2, 3, 4]' %}
					<thead>
						<tr>
							<th>Distribution</th>
							<th>Flags</th>
							<th>Build Info</th>
							<th>Snapshots</th>
							<th>Menu</th>
						</tr>
					</thead>
					<tbody>
						{% for s in r.layout.suiteoption_set.all %}
							{% mbd_parse_distribution r d s as distribution %}
							<tr>
								<td>{{ distribution.name }}</td>
								<td>
									{% if s.uploadable %}<span class="mbd-notice" title="Uploadable (mandatory version regex)">U({{ distribution.mandatory_version_regex }})</span>{% endif %}
									{% if s.experimental %}<span class="mbd-warning" title="Experimental">E</span>{% endif %}
									{% if s.migrates_to %}<span class="mbd-success" title="Migrates to"> =&gt; {{ s.migrates_to.suite.name }}</span>{% endif %}
								</td>
								<td>
									<nav>
										<ul>
											{% if s.uploadable %}
												<li>
													<details>
														<summary>APT sources.list</summary>
														{% mbd_file content=distribution.apt_build_sources_list %}
													</details>
												</li>
												<li>
													<details>
														<summary>APT preferences</summary>
														{% mbd_file content=distribution.apt_build_preferences %}
													</details>
												</li>
											{% endif %}
										</ul>
									</nav>
								</td>
								<td>
									{% if not s.migrates_to and not s.experimental %}
										<details>
											<summary>{{ distribution.snapshots|length }} Snapshots</summary>
											{% mbd_token as snapshots_table_id %}
											<table id="{{ snapshots_table_id }}">
												{% mbd_datatable snapshots_table_id info='false' paging='false' searching='false' %}
												<thead>
													<tr>
														<th>Name</th>
														<th>Menu</th>
													</tr>
												</thead>
												<tbody>
													{% for snap in distribution.snapshots %}
														<tr>
															<td>{{ snap }}</td>
															<td>
																<nav>
																	<ul>
																		<li>{% mbd_api_popup "sources_list" value_codenames=d.base_source.codename value_repositories=r.identity value_suites=s.suite.name value_snapshot=snap %}</li>
																		<li>{% mbd_api_popup "snapshot_delete" value_distribution=distribution.name value_name=snap %}</li>
																	</ul>
																</nav>
															</td>
														</tr>
													{% endfor %}
												</tbody>
												<tfoot>
													<tr>
														<th colspan="2">{% mbd_api_popup "snapshot_create" value_distribution=distribution.name %}</th>
													</tr>
												</tfoot>
											</table>
										</details>
									{% endif %}
								</td>
								<td>
									<nav>
										<ul>
											<li>{% mbd_api_popup "sources_list" value_codenames=d.base_source.codename value_repositories=r.identity value_suites=s.suite.name %}</li>
											{% if s.uploadable %}
												<li>{% mbd_api_popup "port_ext" value_distributions=distribution.name %}</li>
											{% endif %}
										</ul>
									</nav>
								</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</details>
		{% endfor %}
	{% endfor %}
{% endblock %}